spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "**" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: admin
          uri: lb://admin
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix= 1
      #  jackson:
      #    date-format: yyyy-MM-dd HH:mm:ss
      #    time-zone: GMT+8
      #    default-property-inclusion: non_null
      # servlet:
      ##    multipart:
      ##      enabled: true
    ##      max-file-size: 50MB
    ##      max-request-size: 100MB
server:
  port: 8085


eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8767/eureka/
# Security Log
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG

