spring:
  application:
    name: registration
  security:
    user:
      name: admin
      password: admin
server:
  port: 8767
eureka:
  instance:
    hostname: localhost
    instance-id: eureka-8761
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: ${ENABLE_SELF_PRESERVATION:false}
    peer-node-read-timeout-ms: ${PEER_NODE_READ_TIMEOUT_MS:500}
# Security Log
logging:
  level:
    org:
      springframework:
        security: DEBUG
eurake:
  scope: "HXTT_STATION_CAP_DAILY,HXTT_STATION_CAP_MONTH,L_ID"
